### ISSUE TITLE
permission denied

### ISSUE THREAD

**Issue by KimboGilda** [ComputationalMovementAnalysis/computationalmovementanalysis.github.io#1]
@ratnanil I was trying to get onboard with the new `ghp-import` workflow and it seems I do not have access to `ComputationalMovementAnalysis/computationalmovementanalysis.github.io.git`. It seems a little strange.

Maybe I am doing something incorrectly. I suppose that this workflow is also the core of the __package's workflow__. Isn't it?

**Comment by ratnanil** [comment]
No I had to grant you access.. you do now!

**Comment by KimboGilda** [comment]
> 
> 
> No I had to grant you access.. you do now!

Ok thanks
